stages:
  - trigger

trigger-backend:
  stage: trigger
  # only:
  #   changes:
  #     - ./backend/**/*
  trigger:
    include: "/backend/.gitlab-ci.yml"
    strategy: depend

trigger-frontend:
  stage: trigger
  # only:
  #   changes:
  #     - ./frontend/**/*
  trigger:
    include: "/frontend/.gitlab-ci.yml"
    strategy: depend
